---
version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  k2sync:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: /home/pi/timetracker/logs/k2sync.log
    #filename: /home/paconte/devel/timetracker/logs/timetracker.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

root:
  level: INFO
  handlers: [console, k2sync]