- name: Check database exists
  stat:
    path: "{{dst_project}}/src/sqlite3.db"
  register: db_result

- name: Backup database
  fetch:
    src: "{{dst_project}}/src/sqlite3.db"
    dest: "{{src_project}}/backup/sqlite3.db"
    flat: yes
  when: db_result.stat.exists == True

- name: Clean project path
  file:
    state: absent
    path: "{{dst_project}}/"

- name: Create project directory
  file:
    path: "{{dst_project}}"
    state: directory

- name: Create logs directory
  file:
    path: "{{dst_project}}/logs"
    state: directory

- name: Synchronization of source code files
  synchronize:
    src: "{{src_project}}/src"
    dest: "{{dst_project}}"

- name: Restore database
  copy:
    src: "{{src_project}}/backup/sqlite3.db"
    dest: "{{dst_project}}/src/sqlite3.db"
    mode: '0644'
  when: db_result.stat.exists == True

- name: Install pip requirements
  pip:
    requirements: "{{dst_project}}/src/requirements.txt"

- name: Create database if not exists
  ansible.builtin.shell: cd {{dst_project}} && python3 models.py
  when: db_result.stat.exists == False