- name: Drope mysql database
  command: mysql -u root -e "DROP DATABASE IF EXISTS kimai2";
  become: true


- name: Create mysql database
  command: mysql -u root -e "CREATE DATABASE IF NOT EXISTS kimai2";
  become: true


- name: Create mysql kimai2 user
  command: mysql -u root -e "CREATE USER IF NOT EXISTS kimai2@localhost IDENTIFIED BY 'KIMAI2-password-123'";
  become: true


- name: Grant permissions to kimai2 user
  command: mysql -u root -e "GRANT select,insert,update,delete,create,alter,drop,index,references ON kimai2.* TO kimai2@localhost";
  become: true