---
- name: Update and upgrade apt packages
  apt:
    upgrade: 'yes'
    update_cache: yes
  become: true

- name: Install required packages
  apt:
    name:
      - raspberrypi-ui-mods
      - raspberrypi-net-mods
      - python3
      - python3-tk
      - python-imaging-tk
      - emacs
    state: present
    autoclean: yes
  become: true

- name: Check if python3-fingerprint is installed
  command: dpkg-query -W python3-fingerprint
  register: python3_fingerprint_check_deb
  failed_when: python3_fingerprint_check_deb.rc > 1
  changed_when: python3_fingerprint_check_deb.rc == 1

- name: Install python3-fingerprint
  apt:
    deb: python3-fingerprint_1.5_all.deb
  become: true
  when: python3_fingerprint_check_deb.rc == 1