- name: Install timetracker systemd unit file
  copy:
    src: timetracker.service
    dest:  /etc/systemd/system/timetracker.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Start timetracker service
  systemd:
    name: timetracker.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true