- name: Enable raspberry-pi gpio serial port
  lineinfile:
    path: /boot/config.txt
    regexp: '^enable_uart='
    line: enable_uart=1
  become: true
    
- name: Stop and disable serial console service
  service:
    name:    serial-getty@ttyS0.service
    enabled: no
    state:   stopped

- name: Disable serial console
  replace:
    path: /boot/cmdline.txt
    regexp: 'console=serial0,115200'
    replace: ''
    owner: root
    group: root
  become: true

- name: Unconditionally reboot the machine with all defaults
  reboot:
  become: true